# Site settings
title: Piotr Próchnicki
name: Piotr Próchnicki

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/PiotrIT2015
 - title: Gitlab
   url: https://gitlab.com/PiotrIT2017
 - title: LinkedIn
   url: https://www.linkedin.com/in/piotr-prochnicki-7808b2133/?locale=en_US
 - title: Freelancer
   url: https://www.linkedin.com/company/greenroom-7808b2133/?locale=en_US

#Any buzzword skills you want to include
skills:
 - Java  
 - GIT
 - Android
 - Spring
 - SQL
 - Linux
 - Windows

#Work experience is required
roles:
 - title: Office Administrative Employee
   start: November 2018
   end: June 2020
   employer: HR team Sp. z.o.o.
   description: Segregation, recording and creating documentation. Cooperating with other organizational units. Handling of mail. Entering data to a computer. Office service.
 - title: Cisco Services Engineer Intern
   start: July 2017
   end: September 2017
   employer: CISCO SYSTEMS, Krakow, Poland
   description: Achieve practical knowledge in the field of computer networks and programming language Python
 - title: IT Specialist
   start: March 2017
   end: April 2017
   employer: COGITO, Association for the development of psychiatry and environmental care, Krakow, Poland
   description: I took care of all IT devices. My daily work focused on solving different problems with local networks and systems.
 - title: Office Technican
   start: October 2016
   end: December 2016
   employer: Office Computing, City Office, Krakow, Poland
   description: Accounting for hardware and software. Replacing the printer's toner. IT services for conference rooms.
 - title: Serviceman
   start: July 2015
   end: October 2015
   employer: Office Computing, Malopolska Regional Office, Krakow, Poland
   description: Execution of current hungry signaled by IT system users. Service support phone service calls.

#Education is required
education:
 - level: Master of Science
   date: March 2017
   subject: Applied Computer Sciences
   school: University of Science and Technology, Krakow, Poland

#This section is optional (as is the image link below)
apps:
 - name: Postman
   url: https://gitlab.com/PiotrIT2017/postman
   description: app which help shipper
 - name: Reminder
   url: https://gitlab.com/PiotrIT2017/reminder
   description: app for forgetfules
 - name: HealthMonitor
   url: https://github.com/PiotrIT2015/HealthMonitor
   description: app which help maintain balance. First app with MVP architecture.
 - name: localizatormessangerapp
   url: https://gitlab.com/PiotrIT2017/localizatormessangerapp
   description: The next project involved the creation of an Internet messenger with a geolocation service.
 - name: infoapp
   url: https://gitlab.com/PiotrIT2017/infoapp
   description: The order consists in creating an application that sends information to users.
   
#List of interesting Github repo/projects to include - optional
github:
 - PiotrIT2015/Cisco
 - PiotrIT2015/thesis
 - PiotrIT2015/Greenroom

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/8010152/piotr-pr%C3%B3chnicki

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I've develop Java application sinc study.
   <strong>Spring</strong>: I've develop microservices based on Spring sinc I started create project Greenroom.
   <strong>Android</strong>: I was developing apps in this technology i.e. through useme portal<br/><br/>
